/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SignoutIndexImport } from './routes/signout/index'
import { Route as SigninIndexImport } from './routes/signin/index'
import { Route as AuthOnboardingIndexImport } from './routes/auth/onboarding/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignoutIndexRoute = SignoutIndexImport.update({
  id: '/signout/',
  path: '/signout/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any)

const AuthOnboardingIndexRoute = AuthOnboardingIndexImport.update({
  id: '/auth/onboarding/',
  path: '/auth/onboarding/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/signout/': {
      id: '/signout/'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/onboarding/': {
      id: '/auth/onboarding/'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninIndexRoute
  '/signout': typeof SignoutIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninIndexRoute
  '/signout': typeof SignoutIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signout/': typeof SignoutIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/signout' | '/auth/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signout' | '/auth/onboarding'
  id: '__root__' | '/' | '/signin/' | '/signout/' | '/auth/onboarding/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  SignoutIndexRoute: typeof SignoutIndexRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SignoutIndexRoute: SignoutIndexRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin/",
        "/signout/",
        "/auth/onboarding/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin/": {
      "filePath": "signin/index.tsx"
    },
    "/signout/": {
      "filePath": "signout/index.tsx"
    },
    "/auth/onboarding/": {
      "filePath": "auth/onboarding/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
